AssetsGrid/Models/AssetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssetsGrid.Models
{
    public class AssetViewModel
    {
        public int AssetID { get; set; }

        [Display(Name = "Barcode")]
        public string Barcode { get; set; }

        [Display(Name = "Serial-Number")]
        public string SerialNumber { get; set; }
        [Required(ErrorMessage = "Facility-Site is Required")]
        [Display(Name = "Facility-Site")]
        public int FacilitySiteID { get; set; }
        [Display(Name = "Facility-Site")]
        public string FacilitySite { get; set; }
        [Display(Name = "PM-Guide-ID")]
        public string PMGuide { get; set; }
        [Required]
        [Display(Name = "Asset-ID")]
        public string AstID { get; set; }
        [Display(Name = "Child-Asset")]
        public string ChildAsset { get; set; }
        [Display(Name = "General-Asset-Description")]
        public string GeneralAssetDescription { get; set; }
        [Display(Name = "Secondary-Asset-Description")]
        public string SecondaryAssetDescription { get; set; }
        public int Quantity { get; set; }

        [Display(Name = "Manufacturer")]
        public string Manufacturer { get; set; }

        [Display(Name = "Model-Number")]
        public string ModelNumber { get; set; }
        [Display(Name = "Main-Location (Building)")]
        public string Building { get; set; }
        [Display(Name = "Sub-Location 1 (Floor)")]
        public string Floor { get; set; }
        [Display(Name = "Sub-Location 2 (Corridor)")]
        public string Corridor { get; set; }
        [Display(Name = "Sub-Location 3 (Room No)")]
        public string RoomNo { get; set; }
        [Display(Name = "Sub-Location 4 (MER#)")]
        public string MERNo { get; set; }
        [Display(Name = "Sub-Location 5 (Equip/System)")]
        public string EquipSystem { get; set; }
        public string Comments { get; set; }
        public bool Issued { get; set; }

        public SelectList FacilitySitesSelectList { get; set; }
    }
}

AssetsGrid/Models/Assets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AssetsGrid.Models
{
    public class Assets
    {
        [Key]
        public int AssetID { get; set; }

        [Display(Name = "Barcode")]
        public string Barcode { get; set; }

        [Display(Name = "Serial-Number")]
        public string SerialNumber { get; set; }

        [Display(Name = "PM-Guide-ID")]
        public string PMGuide { get; set; }

        [Required]
        [Display(Name = "Asset-ID")]
        public string AstID { get; set; }

        [Display(Name = "Child-Asset")]
        public string ChildAsset { get; set; }

        [Display(Name = "General-Asset-Description")]
        public string GeneralAssetDescription { get; set; }

        [Display(Name = "Secondary-Asset-Description")]
        public string SecondaryAssetDescription { get; set; }
        public int Quantity { get; set; }

        [Display(Name = "Manufacturer")]
        public string Manufacturer { get; set; }

        [Display(Name = "Model-Number")]
        public string ModelNumber { get; set; }

        [Display(Name = "Main-Location (Building)")]
        public string Building { get; set; }

        [Display(Name = "Sub-Location 1 (Floor)")]
        public string Floor { get; set; }

        [Display(Name = "Sub-Location 2 (Corridor)")]
        public string Corridor { get; set; }

        [Display(Name = "Sub-Location 3 (Room No)")]
        public string RoomNo { get; set; }

        [Display(Name = "Sub-Location 4 (MER#)")]
        public string MERNo { get; set; }

        [Display(Name = "Sub-Location 5 (Equip/System)")]
        public string EquipSystem { get; set; }

        public string Comments { get; set; }

        public bool Issued { get; set; }

        
        public int FacilitySiteID { get; set; }

        public virtual FacilitySites FacilitySites { get; set; }


    }
}

AssetsGrid/Controllers/AssetController.cs
using AssetsGrid.Models;
using DataTables.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AssetsGrid.Controllers
{
    
    public class AssetController : Controller
    {
        private ApplicationDbContext _dbContext;

        public ApplicationDbContext DbContext
        {
            get
            {
                return _dbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set
            {
                _dbContext = value;
            }

        }
        public AssetController()
        {

        }

        public AssetController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: Asset
        public ActionResult Index()
        {
            return View(DbContext.Assets.ToList());
        }
        private SelectList GetFacilitiySitesSelectList(object selectedValue = null)
        {
            return new SelectList(DbContext.FacilitySites
                                            .Where(facilitySite => facilitySite.IsActive && !facilitySite.IsDeleted)
                                            .Select(x => new { x.FacilitySiteID, x.FacilityName }),
                                                "FacilitySiteID",
                                                "FacilityName", selectedValue);
        }


        public ActionResult Create()
        {
            var model = new AssetViewModel();
            model.FacilitySitesSelectList = GetFacilitiySitesSelectList();
            return View("_CreatePartial", model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(AssetViewModel assetVM)
        {
            if (!ModelState.IsValid)
                return View("_CreatePartial", assetVM);

            Assets asset = MaptoModel(assetVM);

            DbContext.Assets.Add(asset);
            var task = DbContext.SaveChangesAsync();
            await task;

            if (task.Exception != null)
            {
                ModelState.AddModelError("", "Unable to add the Asset");
                return View("_CreatePartial", assetVM);
            }

            return Content("success");
        }

        public ActionResult Edit(int id)
        {
            var asset = DbContext.Assets.FirstOrDefault(x => x.AssetID == id);

            AssetViewModel assetViewModel = MapToViewModel(asset);

            if (Request.IsAjaxRequest())
                return PartialView("_EditPartial", assetViewModel);

            return View(assetViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AssetViewModel assetVM)
        {

            assetVM.FacilitySitesSelectList = GetFacilitiySitesSelectList(assetVM.FacilitySiteID);
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View(Request.IsAjaxRequest() ? "_EditPartial" : "Edit", assetVM);
            }

            Assets asset = MaptoModel(assetVM);

            DbContext.Assets.Attach(asset);
            DbContext.Entry(asset).State = System.Data.Entity.EntityState.Modified;
            var task = DbContext.SaveChangesAsync();
            await task;

            if (task.Exception != null)
            {
                ModelState.AddModelError("", "Unable to update the Asset");
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View(Request.IsAjaxRequest() ? "_EditPartial" : "Edit", assetVM);
            }

            if (Request.IsAjaxRequest())
            {
                return Content("success");
            }

            return RedirectToAction("Index");

        }

        public async Task<ActionResult> Details(int id)
        {
            var asset = await DbContext.Assets.FirstOrDefaultAsync(x => x.AssetID == id);
            var assetVM = MapToViewModel(asset);

            if (Request.IsAjaxRequest())
                return PartialView("_detailsPartial", assetVM);

            return View(assetVM);
        }

        public ActionResult Delete(int id)
        {
            var asset = DbContext.Assets.FirstOrDefault(x => x.AssetID == id);

            AssetViewModel assetViewModel = MapToViewModel(asset);

            if (Request.IsAjaxRequest())
                return PartialView("_DeletePartial", assetViewModel);
            return View(assetViewModel);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteAsset(int AssetID)
        {
            var asset = new Assets { AssetID = AssetID };
            DbContext.Assets.Attach(asset);
            DbContext.Assets.Remove(asset);

            var task = DbContext.SaveChangesAsync();
            await task;

            if (task.Exception != null)
            {
                ModelState.AddModelError("", "Unable to Delete the Asset");
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                AssetViewModel assetVM = MapToViewModel(asset);
                return View(Request.IsAjaxRequest() ? "_DeletePartial" : "Delete", assetVM);
            }

            if (Request.IsAjaxRequest())
            {
                return Content("success");
            }

            return RedirectToAction("Index");

        }
        private AssetViewModel MapToViewModel(Assets asset)
        {
            var facilitySite = DbContext.FacilitySites.Where(x => x.FacilitySiteID == asset.FacilitySiteID).FirstOrDefault();

            AssetViewModel assetViewModel = new AssetViewModel()
            {
                AssetID = asset.AssetID,
                Barcode = asset.Barcode,
                AstID = asset.AstID,
                Building = asset.Building,
                ChildAsset = asset.ChildAsset,
                Comments = asset.Comments,
                Corridor = asset.Corridor,
                EquipSystem = asset.EquipSystem,
                FacilitySiteID = asset.FacilitySiteID,
                FacilitySite = facilitySite != null ? facilitySite.FacilityName : String.Empty,
                Floor = asset.Floor,
                GeneralAssetDescription = asset.GeneralAssetDescription,
                Issued = asset.Issued,
                Manufacturer = asset.Manufacturer,
                MERNo = asset.MERNo,
                ModelNumber = asset.ModelNumber,
                PMGuide = asset.PMGuide,
                Quantity = asset.Quantity,
                RoomNo = asset.RoomNo,
                SecondaryAssetDescription = asset.SecondaryAssetDescription,
                SerialNumber = asset.SerialNumber,
                FacilitySitesSelectList = new SelectList(DbContext.FacilitySites
                                                                    .Where(fs => fs.IsActive && !fs.IsDeleted)
                                                                    .Select(x => new { x.FacilitySiteID, x.FacilityName }),
                                                                      "FacilitySiteID",
                                                                      "FacilityName", asset.FacilitySiteID)
            };

            return assetViewModel;
        }

        private Assets MaptoModel(AssetViewModel assetVM)
        {
            Assets asset = new Assets()
            {
                AssetID = assetVM.AssetID,
                Barcode = assetVM.Barcode,
                AstID = assetVM.AstID,
                Building = assetVM.Building,
                ChildAsset = assetVM.ChildAsset,
                Comments = assetVM.Comments,
                Corridor = assetVM.Corridor,
                EquipSystem = assetVM.EquipSystem,
                FacilitySiteID = assetVM.FacilitySiteID,
                Floor = assetVM.Floor,
                GeneralAssetDescription = assetVM.GeneralAssetDescription,
                Issued = assetVM.Issued,
                Manufacturer = assetVM.Manufacturer,
                MERNo = assetVM.MERNo,
                ModelNumber = assetVM.ModelNumber,
                PMGuide = assetVM.PMGuide,
                Quantity = assetVM.Quantity,
                RoomNo = assetVM.RoomNo,
                SecondaryAssetDescription = assetVM.SecondaryAssetDescription,
                SerialNumber = assetVM.SerialNumber
            };

            return asset;
        }

        [HttpGet]
        public ActionResult AdvancedSearch()
        {
            var advancedSearchViewModel = new AdvancedSearchViewModel();

            advancedSearchViewModel.FacilitySiteList = new SelectList(DbContext.FacilitySites
            .Where(facilitySite => facilitySite.IsActive && !facilitySite.IsDeleted)
            .Select(x => new { x.FacilitySiteID, x.FacilityName }),
            "FacilitySiteID",
            "FacilityName");

            advancedSearchViewModel.BuildingList = new SelectList(DbContext.Assets
            .GroupBy(x => x.Building)
            .Where(x => x.Key != null && !x.Key.Equals(string.Empty))
            .Select(x => new { Building = x.Key }),
            "Building",
            "Building");

            advancedSearchViewModel.ManufacturerList = new SelectList(DbContext.Assets
            .GroupBy(x => x.Manufacturer)
            .Where(x => x.Key != null && !x.Key.Equals(string.Empty))
            .Select(x => new { Manufacturer = x.Key }),
            "Manufacturer",
            "Manufacturer");

            advancedSearchViewModel.StatusList = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text="Issued",Value=bool.TrueString},
                new SelectListItem { Text="Not Issued",Value = bool.FalseString}
            },
            "Value",
            "Text"
            );

            return View("_AdvancedSearchPartial", advancedSearchViewModel);
        }

AssetsGrid/Views/Asset/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Assets</h1>
                <hr />

                <button type="button" class="btn btn-default btn-md" data-toggle="modal" data-url="@Url.Action("Create","Asset")" id="btnCreateAsset">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                </button>

                <button type="button" class="btn btn-default btn-default btn-md" data-toggle="modal" data-target="#advancedSearchModal" id="advancedsearch-button">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </button>
            </div>

            <div class="panel-body">
                <table id="assets-data-table" class="table table-striped table-bordered"></table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="createAssetModal" tabindex="-1" role="dialog" aria-labelledby="CreateAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="createAssetContainer"> </div>
</div>

<div class="modal fade" id="editAssetModal" tabindex="-1" role="dialog" aria-labelledby="EditAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="editAssetContainer"></div>
</div>

<div class="modal fade" id="detailsAssetModal" tabindex="-1" role="dialog" aria-labelledby="DetailsAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="detailsAssetContainer"></div>
</div>

<div class="modal fade" id="deleteAssetModal" tabindex="-1" role="dialog" aria-labelledby="DeleteAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="deleteAssetContainer"></div>
</div>


@Html.Action("AdvancedSearch")
@section Scripts
{
    <script type="text/javascript">
        var assetListVM;
        $(function () {
            assetListVM = {
                dt: null,
                init: function () {
                    dt = $('#assets-data-table').DataTable({
                        "serverSide": true,
                        "processing": true,
                        "ajax": {
                            "url": "@Url.Action("Get","Asset")",
                            "data": function (data) {
                                data.FacilitySite = $("#FacilitySite").val();
                                data.Building = $("#Building").val();
                                data.Manufacturer = $("#Manufacturer").val();
                                data.Status = $("#Status").val();
                            }
                        },
                        "columns": [
                            { "title": "Bar Code", "data": "BarCode", "searchable": true },
                            { "title": "Manufacturer", "data": "Manufacturer", "searchable": true },
                            { "title": "Model", "data": "ModelNumber", "searchable": true },
                            { "title": "Building", "data": "Building", "searchable": true },
                            { "title": "Room No", "data": "RoomNo" },
                            { "title": "Quantity", "data": "Quantity" },
                            {
                                "title": "Actions",
                                "data": "AssetID",
                                "searchable": false,
                                "sortable": false,
                                "render": function (data, type, full, meta) {
                                    return '<a href="@Url.Action("Edit","Asset")?id=' + data + '" class="editAsset">Edit</a> | <a href="@Url.Action("Details","Asset")?id=' + data + '" class="detailsAsset">Details</a> | <a href="@Url.Action("Delete","Asset")?id=' + data + '" class="deleteAsset">Delete</a>';
                                }
                            }
                        ],
                        "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
                    });
                },
                refresh: function () {
                    dt.ajax.reload();
                }
            }

            $('#btnPerformAdvancedSearch').on("click", assetListVM.refresh);

            // initialize the datatables
            assetListVM.init();

            $("#btnCreateAsset").on("click", function () {
                var url = $(this).data("url");
                $.get(url, function (data) {
                    $('#createAssetContainer').html(data);
                    $('#createAssetModal').modal('show');
                });
            });
            function CreateAssetSuccess(data) {
                if (data != "success") {
                    $('#createAssetContainer').html(data);
                    return;
                }
                $('#createAssetModal').modal('hide');
                $('#createAssetContainer').html("");
                assetListVM.refresh();
            }
            $('#assets-data-table').on("click", ".editAsset", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.get(url, function (data) {
                    $('#editAssetContainer').html(data);
                    $('#editAssetModal').modal('show');
                });
            });

            /**** Edit Asset Ajax Form CallBack ********/

            function UpdateAssetSuccess(data) {
                if (data != "success") {
                    $('#editAssetContainer').html(data);
                    return;
                }
                $('#editAssetModal').modal('hide');
                $('#editAssetContainer').html("");
                assetListVM.refresh();
            }
            $('#assets-data-table').on("click", ".detailsAsset", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.get(url, function (data) {
                    $('#detailsAssetContainer').html(data);
                    $('#detailsAssetModal').modal('show');
                });
            });

            /**** Delet Asset Ajax Form CallBack ********/
            function DeleteAssetSuccess(data) {
                if (data != "success") {
                    $('#deleteAssetContainer').html(data);
                    return;
                }
                $('#deleteAssetModal').modal('hide');
                $('#deleteAssetContainer').html("");
                assetListVM.refresh();
            }
            $('#assets-data-table').on("click", ".deleteAsset", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.get(url, function (data) {
                    $('#deleteAssetContainer').html(data);
                    $('#deleteAssetModal').modal('show');
                });
            });
        });
    </script>

}

AssetsGrid/Views/Asset/_AdvancedSearchPartial.cshtml
    @model AssetsGrid.Models.AdvancedSearchViewModel
    @{
        Layout = null;
    }
    <div>
        <div>
            <div class="modal fade" id="advancedSearchModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Advanced Search</h4>
                        </div>

                        @using (Html.BeginForm("Get", "Asset", FormMethod.Get, new { id = "frmAdvancedSearch", @class = "form-horizontal", role = "form" }))

                        {
                            <div class="modal-body">
                                <div class="form-horizontal">
                                    <hr />
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.FacilitySite,htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-8">
                                            <div class="dropdown">
                                                @Html.DropDownListFor(model => model.FacilitySite, Model.FacilitySiteList, "Any", new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Building, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-8">
                                            <div class="dropdown">
                                                @Html.DropDownListFor(model => model.Building, Model.BuildingList, "Any", new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-8">
                                            <div class="dropdown">
                                                @Html.DropDownListFor(model => model.Manufacturer, Model.ManufacturerList, "Any", new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        <div class="dropdown">
                                            @Html.DropDownListFor(model => model.Status,Model.StatusList , "Both", new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                            </div>

                        <div class="modal-footer">
                            <button id="btnPerformAdvancedSearch" type="button" class="btn btn-default btn-success" data-dismiss="modal">Search</button>
                            <button id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal"> Cancel </button>
                        </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

AssetsGrid/Views/Asset/_AssetsPartial.cshtml
<button type="button" class="btn btn-default btn-md" data-toggle="modal" data-url="@Url.Action("Create","Asset")" id="btnCreateAsset">
    <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span> Add Asset
</button>

AssetsGrid/Views/Asset/_DeletePartial.cshtml
@model AssetsGrid.Models.AssetViewModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
            <h2 class="modal-title">Delete Asset</h2>
            <h5>Are you sure you want to delete this?</h5>
        </div>

        <div class="modal-body">
            <div class="form-group">
                @Html.LabelFor(model => model.GeneralAssetDescription, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.Barcode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GeneralAssetDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />
            @using (Ajax.BeginForm("Delete", "Asset", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "DeleteAssetSuccess" }, new { @class = "form-horizontal", role = "form" }))
            {

      


                <div class="modal-footer">
                    <div class="form-group">
                        @Html.HiddenFor(x => x.AssetID)
                        <div class="col-md-offset-2 col-md-8">
                            <button type="button" class="btn btn-info" data-dismiss="modal"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> </button>
                            <button type="submit" class="btn btn-danger" value="Delete"> <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </button>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>